<?php

namespace DoctrineProxy\__CG__\PhpProjects\SocialDev\Model\Feed;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FeedItemEntity extends \PhpProjects\SocialDev\Model\Feed\FeedItemEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'feedItemId', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'user', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'author', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'url', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'description', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'detailUrl', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'imageUrl', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'timestamp'];
        }

        return ['__isInitialized__', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'feedItemId', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'user', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'author', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'url', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'description', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'detailUrl', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'imageUrl', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\Feed\\FeedItemEntity' . "\0" . 'timestamp'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FeedItemEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFeedItemId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getFeedItemId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedItemId', []);

        return parent::getFeedItemId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): \PhpProjects\SocialDev\Model\User\UserEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor(): \PhpProjects\SocialDev\Model\User\UserEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl(): \PhpProjects\SocialDev\Model\Url\UrlEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetailUrl(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetailUrl', []);

        return parent::getDetailUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', []);

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageUrl', []);

        return parent::getImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageUrl(string $imageUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageUrl', [$imageUrl]);

        return parent::setImageUrl($imageUrl);
    }

}
