<?php

namespace DoctrineProxy\__CG__\PhpProjects\SocialDev\Model\User;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserEntity extends \PhpProjects\SocialDev\Model\User\UserEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'user_id', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'googleUid', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'email', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'username', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'urlIds'];
        }

        return ['__isInitialized__', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'user_id', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'googleUid', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'email', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'username', '' . "\0" . 'PhpProjects\\SocialDev\\Model\\User\\UserEntity' . "\0" . 'urlIds'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogleUid($googleUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogleUid', [$googleUid]);

        return parent::setGoogleUid($googleUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogleUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleUid', []);

        return parent::getGoogleUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function isFullyRegistered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFullyRegistered', []);

        return parent::isFullyRegistered();
    }

    /**
     * {@inheritDoc}
     */
    public function likeUrl(\PhpProjects\SocialDev\Model\Url\UrlEntity $url): \PhpProjects\SocialDev\Model\LikedUrl\LikedUrlEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'likeUrl', [$url]);

        return parent::likeUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function followUser(\PhpProjects\SocialDev\Model\User\UserEntity $user): \PhpProjects\SocialDev\Model\User\UserFollowerEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'followUser', [$user]);

        return parent::followUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function addFollowedUserLikedUrlToFeed(\PhpProjects\SocialDev\Model\LikedUrl\LikedUrlEntity $likedUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFollowedUserLikedUrlToFeed', [$likedUrl]);

        return parent::addFollowedUserLikedUrlToFeed($likedUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function addFollowedUserCommentToFeed(\PhpProjects\SocialDev\Model\Url\UrlCommentEntity $commentEntity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFollowedUserCommentToFeed', [$commentEntity]);

        return parent::addFollowedUserCommentToFeed($commentEntity);
    }

    /**
     * {@inheritDoc}
     */
    public function addUserCommentedOnSharedUrlToFeed(\PhpProjects\SocialDev\Model\Url\UrlCommentEntity $commentEntity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserCommentedOnSharedUrlToFeed', [$commentEntity]);

        return parent::addUserCommentedOnSharedUrlToFeed($commentEntity);
    }

    /**
     * {@inheritDoc}
     */
    public function addUserSharingSameUrl(\PhpProjects\SocialDev\Model\LikedUrl\LikedUrlEntity $likedUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserSharingSameUrl', [$likedUrl]);

        return parent::addUserSharingSameUrl($likedUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function fireNewUserEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fireNewUserEvent', []);

        return parent::fireNewUserEvent();
    }

}
